# config file for the job execution on cluster 

__default__:
    account: "ClinicalMicrobio"
    cpus-per-task: "{threads}"
    time: "12:00:00"
    mem: 16384 # {mem_mb}
    output: "logs/{rule}-%j.out"
    #output: "logs/{rule}.out"

    error: "logs/{rule}-%j.err"
    #error: "logs/{rule}.err"

prokka:
    cpus-per-task: 4


