# config file for the job execution on cluster 

__default__:
    account: "ClinicalMicrobio"
    cpus-per-task: 1
    time: "12:00:00"
    mem: 32768
    #output: "logs/{rule}-%j.out"
    output: "logs/{rule}.out"

    #error: "logs/{rule}-%j.err"
    error: "logs/{rule}.err"

align:
    cpus-per-task: 8


tree:
    cpus-per_tast: 8