# [--snakefile FILE] 
cores: 2048
# [--local-cores N] 
#configfile: "/home/cmkobel/assemblycomparator2/configs/workflow.yaml"

# [--directory DIR] 
keep-going: true 
rerun-incomplete: true
# [--shadow-prefix DIR] 
# [--reason] 
# [--latency-wait SECONDS] 
# [--max-jobs-per-second MAX_JOBS_PER_SECOND] 
# [--greediness GREEDINESS] 
# [--runtime-profile FILE] 
show-failed-logs: true
drmaa: "
    --mem={cluster.mem}
    --cpus-per-task={cluster.cpus-per-task} 
    --time={cluster.time} 
    --account={cluster.account}
    --error={cluster.error} 
    --output={cluster.output}
"

# This should be given as a cli argument
#cluster-config: "/home/cmkobel/assemblycomparator2/configs/slurm/cluster.yaml" 


# [--jobscript SCRIPT] 
jobname: "{name}.{jobid}.snakejob.sh" 
#use-conda: true
#use-singularity: true
# [--conda-prefix DIR] 

latency-wait: 160 # This might seem excessive, but on GenomeDK increasing this value seemed to help with some tentatively failed jobs.


# TODO: clean up this file.
